version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "org.apache.maven.scm:*" # don't touch this, it causes test failures
      - dependency-name: "org.wiremock:wiremock-standalone" # Causes https://github.com/wiremock/wiremock/issues/2778

  - package-ecosystem: "github-actions" # Also update Github actions
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
