quarkus:
  http:
    enable-compression: true
    enable-decompression: true

    # Add CORS
    cors:
      enabled: true
      origins: "/.*/"
  swagger-ui:
    always-include: true
  websocket:
    dispatch-to-worker: true
  hibernate-orm:
    log:
      sql: false
    database:
      generation: ${persistence.hibernate.hbm2ddl.auto:update}
  # graceful shutdown in case Quarkus is still processing requests
  shutdown:
    timeout: 30
  index-dependency:
    pnc-jandex:
      group-id: "org.jboss.pnc"
  log:
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n"
      json:
        enabled: false
        exception-output-type: formatted
    category:
      "org.jboss.pnc":
        level: DEBUG
    level: INFO

# Dependency Analyzer defaults
da:
  pnc-url: ""
  indy:
    indy-url: ""
    indy-group: ""
    indy-group-public: ""
    indy-request-timeout: 3600000
    indy-request-retries: 10
  lookup-modes:
    - name: PERSISTENT
      suffixes:
        - redhat
      increment-suffix: redhat
      build-categories:
        - STANDARD
      artifact-qualities:
        - NEW
        - VERIFIED
        - TESTED
    - name: TEMPORARY
      suffixes:
        - temporary-redhat
        - redhat
      increment-suffix: temporary-redhat
      build-categories:
        - STANDARD
      artifact-qualities:
        - NEW
        - VERIFIED
        - TESTED
        - TEMPORARY
