quarkus:
  application:
    name: dependency-analysis
  http:
    enable-compression: true
    enable-decompression: true

    # Add CORS
    cors:
      enabled: true
      origins: "/.*/"

    auth:
      # required for LDAP: build-time property
      basic: true
  security:
    ldap:
      # enable LDAP: build-time property
      enabled: true
      cache:
        enabled: true
        max-age: 5m
      dir-context:
        url: ldaps://ldap-server.com
      identity-mapping:
        search-base-dn: ou=company.com
  oidc:
    auth-server-url: https://keycloak-host/auth/realms/pncredhat
    client-id: client
    credentials:
      secret: secret
  otel:
    enabled: true
    resource:
      attributes: "sampler_ratio=0.05,service.name=da"
    exporter:
      otlp:
      # Send telemetry data to an opentelemetry-collector
      #endpoint: http://localhost:4317
    traces:
      enabled: true
      # reflect sampling on collector
      sampler:
        ratio: 0.05
    sdk:
      disabled: true

  swagger-ui:
    always-include: true
  websocket:
    dispatch-to-worker: true
  hibernate-orm:
    log:
      sql: false
    database:
      generation: ${persistence.hibernate.hbm2ddl.auto:update}
  # graceful shutdown in case Quarkus is still processing requests
  shutdown:
    timeout: 30
  index-dependency:
    pnc-jandex:
      group-id: "org.jboss.pnc"
  log:
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n"
      json:
        enabled: false
        exception-output-type: formatted
    category:
      "org.jboss.pnc":
        level: DEBUG
    level: INFO

# Dependency Analyzer defaults
da:
  pnc-url: ""
  indy:
    indy-url: ""
    indy-group: ""
    indy-group-public: ""
    indy-request-timeout: 3600000
    indy-request-retries: 10
  lookup-modes:
    - name: PERSISTENT
      suffixes:
        - redhat
      increment-suffix: redhat
      build-categories:
        - STANDARD
      artifact-qualities:
        - NEW
        - VERIFIED
        - TESTED
    - name: TEMPORARY
      suffixes:
        - temporary-redhat
        - redhat
      increment-suffix: temporary-redhat
      build-categories:
        - STANDARD
      artifact-qualities:
        - NEW
        - VERIFIED
        - TESTED
        - TEMPORARY
