quarkus:
  http:
    enable-compression: true
    enable-decompression: true

    # Add CORS
    cors:
      enabled: true
      origins: "/.*/"
  # We also need to configure the oidc-client
  # More here: https://quarkus.io/guides/security-openid-connect-client-reference
  oidc-client:
    auth-server-url: https://keycloak/auth
    client-id: quarkus_app
    credentials:
      secret: secret
    refresh-token-time-skew: 2M
  swagger-ui:
    always-include: true
  websocket:
    dispatch-to-worker: true
  hibernate-orm:
    log:
      sql: false
    database:
      generation: ${persistence.hibernate.hbm2ddl.auto:update}
  # graceful shutdown in case Quarkus is still processing requests
  shutdown:
    timeout: 30
  index-dependency:
    pnc-jandex:
      group-id: "org.jboss.pnc"
  log:
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n"
      json:
        enabled: false
        exception-output-type: formatted
    category:
      "org.jboss.pnc":
        level: DEBUG
    level: INFO

pnc_client_auth:
  type: OIDC # or LDAP
  ldap_credentials:
    path: /mnt/secrets/ldap_credentials # file must be in format: <username>:<password>
