name: Build snapshot version and upload to Maven Central

permissions: {}

on:
  push:
    branches: [ "master" ]

jobs:
    call-snapshot-job:
      uses: project-ncl/shared-github-actions/.github/workflows/maven-snapshot.yml@9735924b878ff3890cfaf16acb28e06531963ebf # v0.0.25
      with:
        project_name: 'project-ncl/dependency-analysis'
      secrets:
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        QUAY_DEVEL_USERNAME: ${{ secrets.QUAY_DEVEL_USERNAME }}
        QUAY_DEVEL_PASSWORD: ${{ secrets.QUAY_DEVEL_PASSWORD }}
